version: '3.4'

services:
  tut2:
    env_file:
      - .env
    container_name: ${IMAGE_NAME}
    image: ${IMAGE_NAME}
    build:
      context: ../../
      dockerfile: ./buildings/develop/Dockerfile
      args:
        - USER_ID_ARG=${USER_ID}
        - USER_NAME_ARG=${USER_NAME}
        - APP_DIR_ARG=${APP_DIR}
    ports:
      - "5678:5678"
    volumes:
      - /home/sermin/docker_sermin/docker_python/tut2/lode:/app/lode

#        - DO_DEBUG_ARG=${DO_DEBUG}
#        - PY_SRC_NAME_ARG=${PY_SRC_NAME}
#      - ./buggy:/opt/buggy
#    environment:
#      - VAR2=compose
